### ISSUE TITLE
Integrations tests don't trigger errors in case of incorrect GraphQL query

### ISSUE THREAD

**Issue by jelisejev** [ctco/nodejs-graphql-template#27]
GraphQL just silently returns "undefined"

**Comment by trioletas** [comment]
@aeldar please investigate if we could fail fast here.

**Comment by aeldar** [comment]
If I understand you right, it is just a matter of not very good example in the current `joke.test.ts`.
```js
const result = await graphql(schema, query, rootValue, context);
const {data} = result;
```
In this code the `data` is `undefined`, but not the `result` returned by `graphql`. By design, it doesn't throw errors in case of incorrect QraphQL query. Neither rejects promise in such a case. It returns an object with a property `errors` which is a list of `GraphQLError`s. So to check if the query is valid we should implicitly check the `errors` property, e.g.:
```js
const result = await graphql(schema, query, rootValue, context);
expect(result.errors).toBeUndefined();
// ...further checks
const {data} = result;
```
Please correct me if I didn't get the point :)

**Comment by aeldar** [comment]
Also I am not sure it makes sense to check every query for errors. If we got `result.data` undefined, then any reasonable expectations should fail anyway.

**Comment by aeldar** [comment]
Probably I am wrong. If `data` is a scalar which expected to be `false` and can be implicitly casted to `false`, then some tests could become false positive in case of errored result (and `data` `undefined`).
But, again, that is probably the problem of the test quality.

**Comment by aeldar** [comment]
Of course, we can create a wrapper for `graphql()` to make it reject the promise in case of errors, and even extract that wrapper into a separate module. Then we will have to apply it to `graphql` in every test suite, or put it onto the global scope inside test setup. Or just import and use it instead of original `graphql`. But I am not sure it is a good idea, as it seems confusing, if in real code we continue to use original `graphql`, which behaves differently.
